Repository MAKENTNU/web, pull requests merged in 2025-05, with the labels that each got.

#756 Fix incorrect and failing reservation rule lists
  CHANGELOG.md
  src/make_queue/api/views.py
Labels: :zap:Quick review:zap:

#749 Usage requirements refactor
  CHANGELOG.md
  src/checkin/views.py
  src/locale/nb/LC_MESSAGES/django.mo
  src/locale/nb/LC_MESSAGES/django.po
  src/make_queue/admin.py
  src/make_queue/forms/course.py
  src/make_queue/migrations/0035_coursepermission_printer3dcourse_course_permissions_and_more.py
  src/make_queue/models/course.py
  src/make_queue/models/machine.py
  src/make_queue/templates/make_queue/course/printer_3d_course_form.html
  src/make_queue/templates/make_queue/course/printer_3d_course_list.html
  src/make_queue/tests/models/test_machines.py
  src/make_queue/tests/models/test_reservation.py
  src/make_queue/tests/views/test_machine_views.py
  src/make_queue/tests/views/test_reservation_views.py
Labels: feature

#757 Deployment
  .github/pull_request_template.md
  CHANGELOG.md
  src/checkin/views.py
  src/locale/nb/LC_MESSAGES/django.mo
  src/locale/nb/LC_MESSAGES/django.po
  src/make_queue/admin.py
  src/make_queue/api/views.py
  src/make_queue/forms/course.py
  src/make_queue/migrations/0035_coursepermission_printer3dcourse_course_permissions_and_more.py
  src/make_queue/models/course.py
  src/make_queue/models/machine.py
  src/make_queue/templates/make_queue/course/printer_3d_course_form.html
  src/make_queue/templates/make_queue/course/printer_3d_course_list.html
  src/make_queue/tests/models/test_machines.py
  src/make_queue/tests/models/test_reservation.py
  src/make_queue/tests/views/test_machine_views.py
  src/make_queue/tests/views/test_reservation_views.py
Labels: deployment
